# Demystifying the Math Behind Machine Learning

In [1]:
import numpy as np
y = np.array([44,21,37])
print (y)
print (y.shape)

[44 21 37]
(3,)


In [2]:
X = np.array([[1.1, 1, 545, 1],[4.6, 0, 345, 2],
              [7.2, 1, 754, 3]])
print (X)

[[   1.1    1.   545.     1. ]
 [   4.6    0.   345.     2. ]
 [   7.2    1.   754.     3. ]]


In [3]:
X = np.array([1.1, 1, 545, 1, 4.6, 0, 345, 2, 
              7.2, 1, 754, 3]).reshape(3,4)
print(X)

[[   1.1    1.   545.     1. ]
 [   4.6    0.   345.     2. ]
 [   7.2    1.   754.     3. ]]


In [4]:
a = np.array([[1, 1],[1, 0]]) 
b = np.array([[1, 0],[0, 1]])
print (a - b)

[[ 0  1]
 [ 1 -1]]


In [5]:
a = np.array([[0, 1],[1, -1]])
print (a * -2)

[[ 0 -2]
 [-2  2]]


In [6]:
X = np.array([[4, 5],[2, 4],[3, 3]])
b = np.array([3,-2])
print(np.dot(X, b))

[ 2 -2  3]


In [7]:
B = np.array([[3, -2],[-2, 5]])
print (np.dot(X, B))

[[ 2 17]
 [-2 16]
 [ 3  9]]


In [8]:
X.transpose()

array([[4, 2, 3],
       [5, 4, 3]])